### ISSUE TITLE
No such file or directory: 'babelnet_v6/ground.gz'

### ISSUE THREAD

**Issue by tuukka** [divyakoyy/codenames#1]
I'm following the setup instructions in the README but the program fails to start. Where should the files like `babelnet_v6/ground.gz` come from?

```bash
$ python codenames.py babelnet
Codenames Configuration:  {'verbose': False, 'visualize': False, 'split_multi_word': True, 'disable_verb_split': True, 'debug_file': None, 'length_exp_scaling': None, 'use_heuristics': True, 'single_word_label_scores': (1, 1.1, 1.1, 1.2), 'use_kim_scoring_function': False, 'use_domain_clues': False}
Building game for  babelnet ...
Traceback (most recent call last):
  File "codenames.py", line 538, in <module>
    save_path="tmp_babelnet_" + str(i))
  File "codenames.py", line 164, in _build_game
    self.weighted_nn[word] = self.embedding.get_weighted_nn(word)
  File "/home/tuukka/codenames/embeddings/babelnet.py", line 206, in get_weighted_nn
    with gzip.open(self.file_dir + word + '.gz', 'r') as f:
  File "/usr/local/lib/python3.7/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/local/lib/python3.7/gzip.py", line 168, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'babelnet_v6/ground.gz'
```

**Comment by divyakoyy** [comment]
We fixed the Google Drive download link to include these BabelNet files. Please re-download and let us know if you still have issues. Thanks!

**Comment by tuukka** [comment]
When I try to follow the new Google Drive link, it says my account does not have access to it.

**Comment by divyakoyy** [comment]
Sorry about that, please check the link now.

**Comment by tuukka** [comment]
Got it running - thank you for your help and the amazing research!
